apiVersion: apps/v1
kind: Deployment
metadata:
  name: citizen-deployment
  labels:
    app: citizen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citizen
  template:
    metadata:
      labels:
        app: citizen
    spec:
      containers:
      - name: citizen
        image: tbusschaert/society-service-citizen:latest
        ports:
        - containerPort: 80
        env:
          - name: ConnectionStrings__CitizenDb
            value: "Server=192.168.1.6,1433;Database=CitizenDb.Dev;User Id=develop;Password=develop;MultipleActiveResultSets=True;"
          - name: MassTransit__Username
            value: "guest"
          - name: MassTransit__Password
            value: "guest"
          - name: MassTransit__Host
            value: "192.168.1.6"
---
apiVersion: v1
kind: Service
metadata:
  name: citizen-service
spec:
  selector:
    app: citizen
  ports:
  - port: 80
    protocol: TCP